### ISSUE TITLE
Possible Withdrawal error

### ISSUE THREAD

**Issue by coreyjallen** [cryptotwenty/smartcontracts#2]
https://github.com/cryptotwenty/smartcontracts/blob/7b6559f646581a6b76e2384589796e421d0ef126/C20.sol#L244

should this be dividing by the denominator instead of the numerator?

**Comment by MatthewFin** [comment]
if the price is 200 tokens per ETH, simplistically that corresponds to 200/1. When withdrawing 200 tokens you would receive 200 * (1/200) = 1 ETH
