### ISSUE TITLE
info@crypto20

### ISSUE THREAD

**Issue by Canaancrypto** [cryptotwenty/smartcontracts#4]
I need a complete low down on this crypto20 funding platform. I want to know those behind the the project before I'll invest my funds.

**Comment by Canaancrypto** [comment]
Are they running any airdrops?

**Comment by MatthewFin** [comment]
Hi Canaancrypto,

We do not do airdrops. You can read more about CRYPTO20 on our website: https://crypto20.com. We also have numerous social media channels, please feel free to reach out if you have any queries.
